# Generated by Django 2.0.2 on 2018-03-07 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('views', '0005_auto_20180307_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
